FROM postgres:latest

# Copy initialization script if needed
# COPY init.sql /docker-entrypoint-initdb.d/

# Set environment variables for PostgreSQL
ENV POSTGRES_DB taxi_data
ENV POSTGRES_USER ybyadav36
ENV POSTGRES_PASSWORD password